name: build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build-macos:
        runs-on: macos-13

        steps:
            - name: Set up Swift
              uses: swift-actions/setup-swift@v2
              with:
                swift-version: "5.10.1"

            - name: Checkout
              uses: actions/checkout@v4

            - name: Build
              run: swift build

            - name: Run tests
              run: swift test
